### ISSUE TITLE
When use 'c14 login'

### ISSUE THREAD

**Issue by ilanmimoun** [scaleway/c14-cli#48]
When do we have to use `c14 login`? Each time by computer or each time we want to use a c14 command line?

**Comment by Daverball** [comment]
I haven't had to use the login command since the first time I've used it around two months back. So I'm guessing they don't really invalidate the oauth token ever, or if they do, then very infrequently. Which makes sense for an API, since you don't really want to have to generate an API token every time you reboot your system, or worse yet for every operation.

**Comment by quentinselle** [comment]
The first time you launch ```c14 login```  your ```access_token```, ```client_id``` and ```client_secret``` are stock  in a json file ```~/.config/c14-cli/c14rc.json```. So you don't need to use ```c14 login``` anymore after this settings set. 
Unless you want to have a new token.
